package com.example.accessdatamysql.controllers;

import com.example.accessdatamysql.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Map;

@Controller
@RequestMapping("/users")
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private UserRepository userRepository;

    @RequestMapping("/create")
    public String create() {
        return "users/create";
    }

    @RequestMapping(value = {}, method = RequestMethod.POST)
    @ResponseBody
    public String store(@RequestParam Map<String, String> request) {
        return "Password: " + request.get("password");
    }
}
